"""empty message

Revision ID: 3af8c29e4dca
Revises: 9c3e58f95f95
Create Date: 2020-11-02 15:42:28.625895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af8c29e4dca'
down_revision = '9c3e58f95f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
