"""empty message

Revision ID: 9c3e58f95f95
Revises: 7b6e96f0e666
Create Date: 2020-11-02 15:33:55.451183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3e58f95f95'
down_revision = '7b6e96f0e666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_request', 'estimated_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_request', sa.Column('estimated_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
