"""empty message

Revision ID: d00e93250b8e
Revises: 35ea995c02d6
Create Date: 2020-11-03 13:15:02.771474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00e93250b8e'
down_revision = '35ea995c02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('service_id', sa.String(), nullable=True))
    op.drop_column('service', 'serviceId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('serviceId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'service_id')
    # ### end Alembic commands ###
